### PR TITLE
Fix sign instant leave issue

### LINKED ISSUE #10: I instant leave the lobby when joining a game via sign
### Details
Plugin version: v1.8.3

Software: Paper Spigot version: git-Paper-333 (1.15.2)

Relevant plugins:

### Console error
```
No errors. Just:
[22:23:25 INFO]: You whisper to Pistonmaster: We wish you a good game!
```

### Configuration file(s)

config.yml: https://pastebin.com/btAWysGQ
I will provide more config files if needed.

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
closes #10

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@montlikadani btw i have one question. How big should such a arena be? I made one 50 blocks in both directions. Is that not enough?

File: src/main/java/hu/montlikadani/ragemode/events/EventListener.java [hunk 1]
```diff
@@ -95,7 +96,9 @@ public void onInteract(PlayerInteractEvent event) {
 				return;
 			}
 
-			GameUtils.joinPlayer(p, GameUtils.getGame(name));
+			Bukkit.getScheduler().scheduleSyncDelayedTask(RageMode.getInstance(), () -> {
+				GameUtils.joinPlayer(p, GameUtils.getGame(name));
+			}, 5L);
```
Comment (montlikadani) [inline src/main/java/hu/montlikadani/ragemode/events/EventListener.java:101]:
```suggestion
Bukkit.getScheduler().scheduleSyncDelayedTask(RageMode.getInstance(), () ->
    GameUtils.joinPlayer(p, GameUtils.getGame(name)), 5L);
```

**Comment by montlikadani** [comment]
> 
> 
> @montlikadani btw i have one question. How big should a rage mode arena be? I made one 50 blocks in both directions. Is that not enough?

As much as it can be. There is no limit to how much distance you can have.
